name: seismic
channels:
  - conda-forge
dependencies:
  - geographiclib=2.0
  - h5py <=3.12.1
  - matplotlib
  - mpi4py<=4.0.1
  - numpy>2, <=2.3.5
  - pip
  - prov
  - pytest
  - pyyaml
  - python>=3.10, <3.13
  - scipy  >=1.7
  - flake8
  - tqdm
  - ipykernel
  - setuptools<70
  - pip:
    - sphinx < 6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - obspy==1.4.2
    - -e .