name: seismic
channels:
  - conda-forge
dependencies:
  - geographiclib
  - h5py
  - matplotlib
  - mpi4py
  - numpy
  - obspy>=1.3
  - pip
  - prov
  - pytest
  - pyyaml
  - python>=3.7
  - scipy<1.9
  - flake8
  - tqdm
  - pip:
    - sphinx
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - -e .