name: seismic
channels:
  - conda-forge
dependencies:
  - geographiclib==2.0
  - h5py<=3.9.0
  - matplotlib<=3.7.2
  - mpi4py<=3.1.4
  - numpy<=1.25.2
  - obspy<=1.4.0, >=1.3.1
  - pip
  - prov
  - pytest
  - pyyaml
  - python>=3.10
  - scipy<=1.11.2
  - flake8
  - tqdm
  - pip:
    - sphinx < 6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - -e .