name: seismic
channels:
  - conda-forge
dependencies:
  - geographiclib
  - h5py
  - matplotlib
  - mpi4py
  - numpy<1.22  # can only be updated once a newer obspy is realeased
  - obspy
  - pip
  - prov
  - pytest
  - pyyaml
  - python=3.8
  - scipy
  - flake8
  - tqdm
  - pip:
    - sphinx
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - -e .