name: seismic
channels:
  - conda-forge
dependencies:
  - geographiclib
  - h5py
  - matplotlib
  - mpi4py
  - numpy
  - obspy>=1.3.1
  - pip
  - prov
  - pytest
  - pyyaml
  - python>=3.7
  - scipy
  - flake8
  - tqdm
  - pip:
    - sphinx < 6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - -e .