name: seismic
channels:
  - conda-forge
dependencies:
  - setuptools
  - geographiclib=2.0
  - h5py
  - matplotlib
  - mpi4py<=4.0.1
  - numpy>2, <=2.4.2
  - pip
  - prov
  - pytest
  - pyyaml
  - python>=3.10, <3.15
  - scipy  >=1.7
  - flake8
  - tqdm
  - ipykernel
  - pip:
    - sphinx < 6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - obspy==1.5.*
    - -e .