#### Project wide parameters
# lowest level project directory
proj_dir : '/home/pm/Documents/PhD/testdata/'
# directory for logging information
log_subdir : 'log'
# folder for figures
fig_subdir : 'figures'
# folder containing preprocessed data
prepro_subdir: 'testnb_preprocessed_ndt'


#### parameters that are network specific
net:
    # list of stations used in the project
    # type: list of strings or string, wildcards allowed
    network : 'D0'
    station : ['BZG', 'ESO', 'KBG', 'KIR']
    # stations : ['D0.BZG', 'D0.ESO', 'D0.KBG', 'D0.KIR']
    # list of channels
    # type: list of strings
    channels : ['HHZ','HHN','HHE']
    # path to the file that stores the coordinates of the stations
    # type: string
    coordinate_file : 'coordinates.txt'
    # file system structure
    # list of strings and lists
    fss : ['/DATA/mseed','%STA',['%sta','%y','%m','%d','??????','.','%cha']]

#### parameters for correlation (emperical Green's function creation)
co:
    # subdirectory of 'proj_dir' to store correlation
    # type: string
    subdir : 'corr_ndt'
    # times sequences to read for cliping or muting on stream basis
    # These should be long enough for the reference (e.g. the standard
    # deviation) to be rather independent of the parts to remove
    # type: string
    read_start : '2015-08-1 00:00:01.0'
    read_end : '2015-08-06 00:00:00.0'
    # type: float [seconds]
    # The longer the faster, but higher RAM usage.
    # Note that this is also the length of the correlation batches
    # that will be written (i.e., length that will be 
    # kept in memory before writing to disk)
    # read_len : 160000
    # read_inc : 160000
    read_len : 86400
    read_inc : 86400

    # required input sampling rate (data with different sampling rate are not used)
    # Not used for miic3
    # type: float [Hz]
    # sampling_rate : 100
    # decimation factor (sampling_rate(correlation)=sampling_rate(date)/decimation)
    # decimation <= 1 mean no decimation
    # type: int
    # Not used for miic3
    # decimation : 5

    # Method to combine different traces
    combination_method : 'betweenStations'

    # preprocessing of the original length time series
    # these function work on an obspy.Stream object given as first argument
    # and return an obspy.Stream object.
    preProcessing : [
                    {'function':'miic.core.stream.stream_filter',
                      'args':{'ftype':'bandpass',
                              'filter_option':{'freqmin':2, #0.01
                                               'freqmax':4}, # 9
                              'parallel':False}},
                     #{'function':'miic.core.stream.stream_mute',
                     # 'args':{'taper_len':100,
                     #         'mute_method':'std_factor',
                     #         'mute_value':3}}
                    ]
    # subdivision of the read sequences for correlation
    # type: presence of this key
    subdivision:
        # type: float [seconds]
        corr_inc : 3600
        corr_len : 3600
        # recombine these subdivisions
        # unused at the time
        # type: boolean
        recombine_subdivision : True
        # delete
        # type: booblean
        delete_subdivision : False
    # Taper the time windows with a 5% Hann taper on each side. If this is True,
    # the time windows will just simply be prolonged by the length of the taper,
    # so that no data is lost
    taper: False

    # parameters for correlation preprocessing
    corr_args : {'TDpreProcessing':[#{'function':'miic3.correlate.correlate.detrend',
                                    # 'args':{'type':'constant'}},
                                   #{'function':'miic.core.pxcorr_func.TDfilter',
                                   # 'args':{'type':'bandpass','freqmin':0.01,'freqmax':4}},
                                    #{'function':'miic.core.pxcorr_func.mute',
                                    # 'args':{'taper_len':100.,
                                           # 'threshold':1000, absolute threshold
                                    #         'std_factor':3,
                                    #         'filter':{'type':'bandpass','freqmin':2,'freqmax':4},
                                    #         'extend_gaps':True}},
                                   {'function':'miic3.correlate.correlate.clip',
                                    'args':{'std_factor':3}},
                                   ],
                 'FDpreProcessing':[
                                    {'function':'miic3.correlate.correlate.spectralWhitening',
                                     'args':{'joint_norm':False}},
                                    {'function':'miic3.correlate.correlate.FDfilter',
                                     'args':{'freqs':[0.01,0.02,9,10]}}
                                    ],
                 'lengthToSave':100,
                 'center_correlation':True,      # make sure zero correlation time is in the center
                 'normalize_correlation':True,
                 'combinations':[],
                 'direct_output':{'function':'convert_to_matlab',
                                  'base_name':'trace'}
                }

    # Component rotation (only possible if 'direct_output' is not in 'corr_args')
    # type: string ['NO', 'ZNE->ZRT', 'NE->RT']
    rotation : 'NO'

