name: build
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: seismic
          environment-file: environment.yml
          python-version: '3.12'
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      # - name: Lint
      #   shell: bash -l {0}
      #   run: |
      #       conda install flake8
      #       python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #       python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install pytest
            pytest tests
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install flake8
            python formatting_test/test_code_formatting.py