name: build
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: seismic
          environment-file: environment.yml
          python-version: '3.12'
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install pytest
            pytest tests
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install flake8
            python formatting_test/test_code_formatting.py